<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Untitled Document</title>
</head>

<body>





      
              
<!--  Production Staff begin  -->
	<h2 class="storyHead">Orchestra</h2>
			<ul><li type="disc">CONDUCTOR</li> 
			<dt><a href="#CAROL FREED">Carol Freed</a></dt>
			
			<li type="disc">VIOLIN</li>
				<dt>Mark Frankel, Concertmaster</dt>
			  <dt>Darrin McBride,
					Hazel Edwards,
					Norman Ellman,<br />
				  Carl Hemmingsen,
					Melitta Alle,
					Elliott Moore,
					<br />
			  Janet Baker </dt>
			<li type="disc">VIOLA</li> 
				<dt>Joanne Damasco, Crystal McFarland, Ruth Miller Cox,<br />
			 Jennifer Cox</dt>
			<li type="disc">CELLO</li>
				<dt>William Dorwart, Marilyn MacRae, Susan Altschuler</dt>
			<li type="disc">BASS</li>
				<dt>Faye Kahmer, George Kahmer, Ann Boohar</dt>
			<li type="disc">FLUTE</li>
				<dt>John Kauffman, Roberta Goren, Debbie Meltz</dt>
			<li type="disc">CLARINET</li> 
				<dt>Jeri Greenfield, Merv Richards, Jill Zhuraw</dt>
			<li type="disc">OBOE</li> 
				<dt>Michael Holtz, Linda McAlpin</dt> 
			<li type="disc">BASSOON</li>
				<dt>Don Greenfield</dt>
			<li type="disc">TRUMPET</li>
				<dt>Allen Tollen, Jeanine Jochems, Michael Jones<br />
                Mike Goodkin</dt>
			<li type="disc">TROMBONE</li>
				<dt>Don Matheson</dt>
			<li type="disc">EUPHONIUM</li>
				<dt>Lynda Chen</dt>
			<li type="disc">FRENCH HORN</li>  
				<dt>Donna Winquist, Ellen Kane, Jacqueline Conway</dt>
			<li type="disc">PERCUSSION</li> 
				<dt>Paul M. Sherin, Joanne Preston</dt>
			<li type="disc">REHEARSAL PIANIST</li>
				<dt><a href="#SHARON KOPE">Sharon Kope</a>, Bruce Bogdanoff</dt>
	</ul><br />

			<h2 class="storyHead">Production Staff</h2>
				<ul>Producer - <a href="#BRUCE CONLEY">Bruce Conley</a></ul>
				<ul>
				  Co-Stage Managers - <a href="#BARB MATHESON">Barb Matheson</a>, <a href="#BARBARA MASTRONARDA">Barbara Mastronardo</a>
				</ul>
				<ul>Set Designer - <a href="#KEN CLARK">Ken Clark</a></ul>
				<ul>Set Construction - <a href="#BOB ALLEN">Bob Allen</a> (co-chair), <a href="#KEN CLARK">Ken Clark</a> (co-chair),<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="#RINO PELLISSIER">Rino Pellissier</a></ul>
<ul>Sound Design - <a href="#SAMUEL HAINES">Samuel Walker Haines, Jr.</a></ul>  
				<ul>Lighting Design - <a href="#KATHY MICHAEL">Kathy Michael</a></ul>  
				<ul>Properties - <a href="#JOYCE MALIN">Joyce Malin</a>, <a href="#ERMA MCEWEN">Erma McEwen</a></ul>
				<ul>
				  Costumes - <a href="#JANICE MANLEY">Janice Manley</a> (chair), Sonja Allen, <br />  
				  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Mary Jane Clark, Lillian A. Pellissier,<br />
                   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tina Dahms, Ken Clark, Bob Allen, <br />
					 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Rino Pellessier
    </ul>
				<!-- <ul>Makeup Designer - <at href="#ROBERT MOORE">Robert Moore</a></ul>-->
				<ul>Graphics Design - <a href="#BILL MICHAEL">Bill Michael</a>
				</ul>
             </b>

<!-- Production Staff end -->



<!--  CAST BIOS  -->

<div>

		<li><a name="JENNIFER ANDREWS"></a><b>Jennifer Andrews <i>(Rapturous Maiden)</i></b> is excited to be back with Rose Valley Chorus & Orchestra for another show. In addition to Patience, she has performed in the chorus of several other shows including <i>Oklahoma!</i>, <i>The Yeomen of the Guard</i>, <i>H.M.S. Pinafore</i>, <i>The Gondoliers</i> and <i>Trial by Jury</i>. Jennifer sings with the worship team at Calvary Chapel of Delaware County. When she isn’t singing, she is an Autistic Support teacher for the Delaware County Intermediate Unit. She thanks her voice instructor, Kathryn Armour of Wilmington, DE for her wonderful teaching and Rose Valley Chorus & Orchestra for inviting her to sing with them again! She looks forward to more shows with Rose Valley Chorus in the future. <a href="#top">Back to top</a></li>
        <li><a name="SHEILA BELL"></a><b>Sheila Bell <i>(Rapturous Maiden, Grants)</i></b> has been a chorus member for the G&S productions since first appearing as a fairy in <i>Iolanthe</i>, her first show in 1987 and is always impressed by the level of professionalism and commitment of everyone involved. She also enjoys participating in Music in the Schools and the newly formed RVCO show chorus. <a href="#top">Back to top</a></li>
		<li><a name="PERI BERMAN"></a><b>Peri Berman <i>(Rapturous Maiden)</i></b> This is Peri’s second show with RVCO having previously performed as Ellen in <i>Oklahoma!</i>  Other roles include Screeching Soprano, Wife, and the front of the Camel in <i>Joseph and the Amazing Technicolor Dreamcoat</i>,  Rose Lennox (<i>Secret Garden</i>), Ethel Toffelmeir (<i>Music Man</i>), Hope Diamond (<i>Dancing Princesses</i>), and Madame Azure (<i>Pinocchio</i>). Peri is a music teacher and keeps busy writing scripts for her students' winter and spring performances. She holds a degree in Music Education from Temple University and is currently working on completing her Masters in Music Education/Kodaly Certification from West Chester University. <a href="#top">Back to top</a></li>  
		<li><a name="CHRIS CAPITOLO"></a><b>Chris Capitolo <i>(Solicitor) </i></b> is happy to be returning to Rose Valley Chorus after participating as a chorus member in <i>Oklahoma!</i> His previous theater experience includes <i>The Pirates of Penzance</i> twice, once in high school and once in college, so he's very happy to finally be in a different G&S show. He'd like to thank everyone involved for giving him a chance to be a part of this production.. <a href="#top">Back to top</a></li>  
<li><a name="KEN CLARK"></a><b>Ken Clark <i>(Set Construction Chair)</i></b> was first listed under Costumes for <i>Kiss Me, Kate</i> in 1998.  After lugging costumes, installing grommets, and posing occasionally as a 'male model', he explored other avenues and proceeded through Stage Crew to Set Construction Crew to Set Construction Chair which he did for <i>Patience</i>, <i>Carousel</i>, <i>H.M.S. Pinafore</i>/<i>Cox and Box</i>, <i>The Red Mill</i>, <i>The Pirate of Penzance</i>, <i>MAME</i>, <i>The Mikado</i>, <i>The Merry Widow</i>, <i>Ruddigore</i>, and <i>H.M.S Pinafore</i>, <i>The Yeomen of the Guard</i> again.  He was theset desinger for <i>The Yeomen of the Guard</i>. Ken has done bit parts on stage: a policeman in <i>Hello, Dolly!</i>, a suspicious character in <i>Guys and Dolls</i>, and a clergyman in <i>The Red Mill</i>. <a href="#top">Back to top</a></li>  
		<li><a name="BRUCE CONLEY"></a><b>Bruce Conley <i>(Dragoon Guard/President/Producer)</i></b> was Ike Skidmore in <i>Oklahoma!</i>, Samuel Zapp in <i>Plain and Fancy</i>, Bogdanowitsch in <i>The Merry Widow</i>, Ralph Devine in <i>MAME</i>, Dirk in <i>The Red Mill</i>, and David Bascombe in <i>Carousel</i>. A chorus member since 1988, he has also enjoyed performing minor roles in many other  past shows.  In addition to serving as  president of RVCO, Bruce also wears many hats offstage, including producing this show. He especially thanks his wife, Rae, for her help and support and his aunt, Thelma Loving, for inspiring his musical interests. <a href="#top">Back to top</a></li>
		<li><a name="WILLIAM DAHMS"></a><b>William Dahms <i>(Dragoon Guard)</i></b> &quot;Willy&quot; is delighted to be performing again with RVCO. He thinks it’s remarkable how clearly one remembers his old Drill Sergeant when the need arises.  He has been a Gilbert and Sullivan fan for years, but only started performing their work in 2002.   Since then, he has performed in eleven out of the fourteen operettas that the pair wrote, and is still hoping to get it right at least once.  He thanks his understanding wife for letting him out at night to dance with other women. <a href="#top">Back to top</a></li>        
		<li><a name="TOM DODDS"></a><b>Tom Dodds <i>(Dragoon Guard)</i></b> first joined RVCO in 2000 for Yeomen of the Guard as the priest, a non-singing role.  It was so much fun he joined the chorus for many shows since then and has now come full circle to enjoy being a dragoon.  He happily participates in Music in the Schools and the RVCO show chorus. <a href="#top">Back to top</a></li>
	  <li><a name="CAROL FREED"></a><b>Carol Freed<i> (Music Director/Conductor)</i></b> started piano at the age of six and was music director first as a senior at Lower Merion High School.  Since then she has been music director/conductor for many local theater groups.  She joined RVCO in 1977 as accompanist and became music director and conductor with The New Moon production in 1985.  Her longevity with RVCO has now earned her the distinction of Life Member.  "What a privilege to lead such a wonderful and talented group of people, both actors and orchestra."  Off the podium, she sells real estate with Weichert Realtors and does vocal coaching.  "Thanks to my husband, Marvin, for supporting me, always." <a href="#top">Back to top</a></li>
		<li><a name="PAULA GONZALEZ"></a><b>Paula Gonzalez <i>(Rapturous Maiden)</i></b> is performing for the first time with the Rose Valley Chorus. She was recently seen performing in<i> The Gondoliers</i> and <i>The Pirettes of Penzance</i>,  with the Ardensingers. This Fall, she can also be seen singing with the choir at St. Peter the Apostle church in New Castle, Delaware, and performing in the Ardensingers'<i> Fezziwig's Christmas Party</i> and the Concord Concert Choir's performance of excerpts from Handel's<i> The Messiah</i>. When she isn't singing, she spends her days working for Produce Marketing Association in Newark, Delaware, and can sometimes be found playing tennis and spending time with her husband. <a href="#top">Back to top</a></li>
    <li><a name="RYAN GOULDEN"></a><b>Ryan Goulden <i>(Archibald Grosvenor)</i></b> was last seen on the Rose Valley stage as Will Parker in <i>Oklahoma!</i> Other recent roles  include Marco in <i>The Gondoliers</i> (Ardensingers), Col Fairfax in <i>The Yeomen of the Guard</i> (RVCO), and Jaques Strap in <i>Vintage with a Vengeance</i> (RVCO). Upcoming projects include music directing <i>HMS Pinafore</i> at Thespis Etc., assistant music directing <i>My Fair Lady</i> at RVCO, and serving on the Executive Board for Ardeinsingers. Ryan remains eternally grateful to his immediate and extended family for all their love and support (especially to Brian) ;-) <a href="#top">Back to top</a></li>
        <li><a name="JENNIFER GRAF"></a><b>Jennifer Graf <i>(Patience)</i></b> soprano, is at home in many vocal genres including opera, operetta, oratorio, early music, and musical theatre. Roles with RVCO include Laurey (<i>Oklahoma!</i>), Elsie (<i>The Yeomen of the Guard</i>), Josephine (<i>HMS Pinafore</i>), Anna Glawari (<i>The Merry Widow</i>), and Mabel (<i>The Pirates of Penzance</i>).  Some of her other favorite roles performed include Pamina (<i>The Magic Flute</i>), Giulietta (<i>I Capuleti e i Montecchi</i>), Blonda (<i>Die Entführung aus dem Serail</i>), Musetta (<i>La Boheme</i>), Frasquita (<i>Carmen</i>), and Kathie (<i>The Student Prince</i>). Additional musical theatre credits include <i>Meet Me in St. Louis</i> and <i>Camelot</i>. Ms. Graf sang the soprano solos in Vivaldi’s Gloria and Magnificat and in Mozart’s Requiem with the Pennsylvania Sinfonia Orchestra and was first soprano soloist for Beethoven’s Choral Fantasy with the Philadelphia Classical Symphony. She has performed as soprano soloist in Bach’s St. Matthew Passion at the Kimmel Center in Philadelphia, in Handel’s <i>Messiah</i>, Bach’s <i>Magnificat</i>, and Vivaldi’s <i>Magnificat</i>, all with the Ama Deus Ensemble. The Ama Deus Ensemble also featured her in the solo soprano <i>Cantata #202</i> and the <i>Missa Brevis</i>, both by Bach. In 2007, Jennifer performed the role of Phyllis in <i>Iolanthe</i> and the International Gilbert and Sullivan Festival in Buxton, England, where she was nominated for the award of Best Female Voice in Festival. She returned to the festival in 2008 to sing Mabel in <i>The Pirates of Penzanc</i>e. Jennifer has released three solo CD recordings: Tidings of Christmas (2006), Echoes of Christmas Past (2009), and Voices of Spring (2010.)  Echoes of Christmas Past was chosen as Top Pick of 2009 by ChristmasReviews.com. Ms. Graf can also be heard on Vox Ama Deus’ release of Dido and Aeneas singing the role of 1st Witch, released on the Lyrichord label. She is founder and general director of Olde Towne Carolers, specializing in holiday performances and entertainment. Ms. Graf, a native of Quakertown, Pennsylvania, earned her Master’s Degree from The New England Conservatory of Music in Vocal Performance.

<a href="http://www.jennifergraf.com" target="_blank">www.jennifergraf.com</a>. <a href="#top">Back to top</a></li>
		<li><a name="SAMUEL HAINES"></a><b>Samuel Walker Haines, Jr. <i>(Sound Design/Operation)</i></b> Sam Haines has had the pleasuure of holding the position of Sound Engineer for the RVCO for the past three seasons.  He resides in Chalfont, PA where he runs Broader Horizon Recording Studio.  He currently works in an in-house studio band creating music based around the Native American flute.  Sam looks forward to another exciting production with RVCO! <a href="#top">Back to top</a></li>
		<li><a name="MARIN HITCH"></a><b>Marin Hitch<i> (Rapturous Maiden)</i></b> is very excited to be back on stage with Rose Valley Chorus! She recently graduated from West Chester University with a degree in Music Education, minor in Music History, and concentrated in flute performance. She studied with Dr. Kimberly Reighley.  She has performed with Rose Valley Chorus and Orchestra for their recent production of <i>Oklahoma!</i> as well as with Chester County Gilbert and Sullivan Society in a production of <i>Trial By Jury</i>. She was also in <i>The Gondoliers</i> with The Ardensingers this past spring. Marin teaches private flute lessons at Taylor's Music Store in West Chester. <a href="#top">Back to top</a></li>		
        <li><a name="ROGER JONES"></a><b>Roger F. Jones <i>(Dragoon Guard)</i></b> is performing with RVCO for the third time in four years (<i>Ruddigore</i> as the Knight in Armor, and <i>HMS Pinafore</i>, chorus).  He is a long-time Gilbert & Sullivan buff, having been taken to see D’Oyly Carte Company performances as a child.  At Haverford High School, he performed in <i>The Pirates of Penzance</i>, <i>The Mikado</i>, and <i>Iolanthe</i> (as Lord High Chancellor).  He has sung for over 35 years in church choirs and takes part annually in the Ocean Grove Church Choir Festival and the Philadelphia Welsh Guild’s Thanksgiving Gymanfa Ganu (Welsh hymn festival).  When not indulging his passion for music or enjoying his family, Roger is an international industrial consultant, author, and lecturer.  He and his wife, Caryl, recently celebrated their 58th wedding anniversary, and have three children (plus spouses) and seven grandchildren, a number of whom will be seeing this show!  “It is a truly great pleasure to perform with such a talented and dedicated group.  I have attended and thoroughly enjoyed RVCO’s Gilbert & Sullivan productions for decades, and finally found my place was on the stage rather than in the audience!” <a href="#top">Back to top</a></li>
        <li><a name="WAYNE JONES"></a><b>WAYNE Jones <i>(Dragoon Guard)</i></b> is very exited to be performing with RVCO in his first Gilbert and Sullivan production. This will be his second show with RVCO as last year he performed in <i>Oklahoma!</i> Wayne is a member of the St. Joseph Catholic Church in Aston and has been a Cantor there for three years and a member of the Choir for ten years. He also is a member of the St. James Alumni Choir the Blue and Grey Voices and is a soloist for the Choir. <a href="#top">Back to top</a></li>
		<li><a name="DOUG KURTZE"></a><b>Doug Kurtze <i>(Dragoon Guard)</i></b> is wearing the RVCO uniform for the second time, having been a Yeoman of the Guard last fall.  He has sung chorus parts in <i>Amahl and the Night Visitors</i>, <i>La Perichole</i>, and <i>Pagliacci</i> with the Fargo-Moorhead Civic Opera, and a number of works with the Main Line Ecumenical Choir and Fanshawe Chorus London (Ontario).  He sang, danced, and played the Fool (that's a role) in the Philadelphia Christmas Revels, and played Mary (aka Betty) in Wassail! in London.  In calmer moments he dances with the Kingsessing Morrismen. <a href="#top">Back to top</a></li>
	  <li><a name="JOYCE MALIN"></a><b>Joyce Malin <i>(Properties Co-chair)</i></b> has been a member of the Rose Valley Chorus & Orchestra family since 1992. Being Properties chairperson gives her an excuse to roam all the yard sales, flea markets, and second hand shops she can. "Many thanks to Erma for all her help." <a href="#top">Back to top</a></li>
       <li><a name="BARBARA MASTRONARDO"></a><b>Barbara Mastronardo <i>(Co-Stage Manager)</i></b> My first experience with this organization was as an audience member at the early 90’s performance of <i>My Fair Lady</i>.  I was so impressed with the professional caliber of that production.   The entire cast, crew and orchestra were just amazing.  As I related my experience to my friend, Carol Freed, she urged me to look into becoming a member of the RVCO stage crew.  As a crew member for various G&S and Broadway shows since then, I have come to know that excellence in all aspects of theater production is the standard of performance for RVCO.  The camaraderie of all of the disciplines of production is superb.   Bob Allen and Barbara Matheson have been excellent mentors to me.  What a pleasure to work with them!  While RVCO offers me a wonderful work experience in the world of “Make Believe,” my business world is as a Real Estate Broker with Weichert Realtors, Media office. <a href="#top">Back to top</a></li>
 <li><a name="BARB MATHESON"></a><b>Barb Matheson <i>(Co-Stage Manager)</i></b> has appeared backstage as Bobette in numerous RVCO shows, including favorites Hansel and Gretel, Carousel, The Red Mill and Mame.  After playing "roles" in business management, she discovered that she was happiest dressed in black, and (mostly) out of sight! Between shows, she likes to travel with her husband, Don, a long-time RVCO member who plays trombone in the orchestra. <a href="#top">Back to top</a></li>
		  <li><a name="ERMA MCEWEN"></a><b>Erma McEwen <i>(Properties Co-chair)</i></b> has assisted in props and stage crew for several years with RVCO. She's happy to work with such a great crew and cast. <a href="#top">Back to top</a></li>		
		  <li><a name="JACK MCEWEN"></a><b>Jack McEwen <i>(Dragoon Guard,Treasurer)</i></b> was Ike Pilersheim in <i>Plain and Fancy</i>, Piet in <i>The Red Mill</i>, Liver Lips Louie in <i>Guys and Dolls</i>, and Bob Barking in <i>Me and My Girl</i>.  "This is my 12<sup>th</sup> season with RVCO.  It's always a great time." <a href="#top">Back to top</a></li>
		<li><a name="Bill MICHAEL"></a><b>Bill Michael <i>(Graphic Designer, Webmsster)</i></b> is happy to be involved  behind the pages for this show. His two children, often seen on the RVCO stage, keep him busy. &quot;Thanks for letting me fulfill some of my dreams<i></i>.&quot; <a href="#top">Back to top</a></li>          		
<li><a name="KATHY MICHAEL"></a><b>Kathy Michael <i>(Lighting Designer)</i></b> is a long-time member, who has previously worked as Lighting Designer, Stage Manager, House Manager, and stage crew for many performances. Previous lighting designs include <i>The Merry Widow</i>, <i>The Gondoliers</i>, <i>The Fantastics</i>, <i>Godspell </i>and Oklahoma!<i></i>. <a href="#top">Back to top</a></li>          		
		<li><a name="RAYMOND MURPHY"></a><b>Raymond Murphy <i>(Colonel Calverley)</i></b> is honored to reprise his role as the Colonel with RVCO.  He appeared as Wilfred Shadbolt in last years <i>The Yeomen of the Guard</i>, and has performed many other roles, both offstage and on, with local theatre groups.  He is a Pennsylvania Certified Horticulturist, and works as a gardener for Nemours Mansion and Gardens in Wilmington, DE.  He is deeply indebted to his wife, Janet, for her supportive patience, and is thankful for all of the blessings he has received through family, friends, and encouraging audience members. <a href="#top">Back to top</a></li>
	  <li><a name="EDWIN NEALLEY"></a><b>Edwin Nealley <i>(Reginald Bunthorne)</i></b> returns to Rose Valley to play Bunthorne, and to peruse cruel life from the opposite bank of the aesthetic stream.  Past G&S roles with RVCO include Grosvenor in the 2004 production of Patience, Jack Point (<i>The Yeomen of Guard</i>), Sir Joseph Porter (<i>H.M.S. Pinafore</i>), and Maj. Gen. Stanley (<i>The Pirates of Penzance</i>).  He also performed in RVCO productions of <i>The Merry Widow</i>, <i>Me and My Girl</i>, <i>Plain & Fancy</i> and the murder mystery, <i>Vintage with a Vengeance</i>.  Other recent roles include Arac (<i>Princess Ida</i>) for Thespis Etc., Luiz (<i>The Gondoliers</i>) for Ardensingers, Capt. Corcoran (<i>H.M.S. Pinafore</i>) for Bucks Cty. G&S and J.W. Wells (<i>The Sorcerer</i>) for G&S Soc. of Chester Cty. Ed has performed in all 14 Gilbert & Sullivan operettas and in more than 40 G&S productions since his start in college under the baton of Bruce Montgomery.  This is his 20th production with Rose Valley and he is grateful for the many years of enjoyment, most especially because Rose Valley is where he met his lovely wife, Kate, and performs onstage with his talented daughter, Sara. <a href="#top">Back to top</a></li>
		<li><a name="KATHERINE NEALLEY"></a><b>Katherine P. Nealley <i>(Stage Director)</i></b> is pleased to return to RVCO to direct <i>Patience</i>, perhaps her favorite of the G&S canon. <i>Patience</i> marks her seventh show as Stage Director here, most recently having directed <i>The Yeomen of the Guard</i> (2010), <i>The Merry Widow</i> (2008), and <i>The Pirates of Penzance</i> (2006), as well as previous productions of <i>Cox & Box</i>, <i>Brigadoon</i>, and <i>H.M.S. Pinafore</i>.  Kate has also directed <i>The Mikado</i>, <i>Princess Ida</i>, <i>H.M.S. Pinafore</i>, <i>Trial by Jury</i>, and <i>Brigadoon</i> for other local theater groups, and has frequently choreographed for area High Schools.  Kate danced professionally in her youth, and has a lifelong interest in social dance forms.  Kate and her husband Edwin met in the Rose Valley production of <i>Ruddigore</i> in 1990, and their talented daughter Sara joins them onstage in this production. <a href="#top">Back to top</a></li>
        <li><a name="SARA NEALLEY"></a><b>Sara Nealley <i>(Lady Saphir)</i></b> has been interested in G&amp;S since before she was born, and she is thrilled to return to Rose Valley Chorus as Saphir, after playing Kate in the 2010 production of <i>The Yeomen of the Guard</i>.  She recently played Gianetta (<i>The Gondoliers</i>) with The Ardensingers, Sandman/Dew Fairy (<i>Hansel &amp; Gretel</i>) with Shannondell Opera Theater, Peep-Bo (<i>The Mikado</i>) with both Thespis Etc. and Bucks County G&amp;S Society, Lily Craven (<i>The Secret Garden</i>) with Drexel Hill Church Players, and has also performed with Opera Delaware (<i>Carmen</i>), G&amp;S Society of Chester County, and with Philadelphia G&amp;S Union and SavoyNet at the International G&amp;S Festival in England.  She is a member of the Haverford H.S. Chamber Singers, and is also a member of the Upper Darby Summer Stage Shooting Stars.  She was selected for the P.M.E.A. (PA) All-State Honor Choir in 2011.  Sara studies voice with Andrea Broido. <a href="#top">Back to top</a></li>
	   <li><a name="CHRIS RUBINO"></a><b>Chris Rubino <i>(Dragoon Guard)</i></b> is proud to be making his debut with RVCO. He saw his first G&S performance from the pit orchestra of <i>H.M.S. Pinafore</i> and has been hooked ever since. Chris enjoys many fond memories of singing and dancing with the Penn Glee Club, as well as in Penn Singers’ production of <i>Utopia Limited</i>, where he met his wife Meagan in 2003. Most recently, he performed in the Philadelphia Gilbert & Sullivan Union’s production of<i> The Sorcerer</i> at the International Gilbert & Sullivan Festival in Gettysburg, PA. Chris looks forward to making his second appearance with RVCO in <i>My Fair Lady</i> next spring. “Much love to Meagan, and our little son Marc, for continuing to inspire me always. <a href="#top">Back to top</a></li>
		<li><a name="DIANE RUNKEL"></a><b>Diane Runkel <i>(Rapturous Maiden)</i></b> Diane is beginning her fifth season with RVCO and has thoroughly enjoyed being on stage for this production. She loves the music, treasures the friendships, and finds the matter of all the memorization a challenge. She especially appreciates her husband, Bill who is responsible for encouraging her to get into this in the first place! She apologizes for the weeks of torture she puts him through in the process of learning a new show! Thanks Bill!<a href="#top"> Back to top</a></li>
		<li><a name="SALLY SAPEGA"></a><b>Sally Sapega<i> (Rapturous Maiden)</i></b> loves being part of RVCO shows! What keeps her coming back is the fun of being onstage and the many wonderful friendships she has formed over the years. Sally has also appeared in shows with Footlighters Theater, Thespis, Etc., and Barnstormers Theater, and is a member of the choral group Schola Cantorum. She thanks her family and friends for all their support and encouragement. <a href="#top">Back to top</a></li>
		<li><a name="RANDE SAXE"></a><b>Rande Saxe <i>(Rapturous Maiden,Board Member)</i></b> – is loving every minute of working with such an extremely talented cast. She is very content with life now as a retired vocal elementary music teacher for 36 years in the North Penn School district in Springfield Montgomery county. Being in the RVCO shows since 2006  is a  real highlight. Each production is more enjoyable than the next. These performances are dedicated to the three
<a href="#top">Back to top</a></li>
		<li><a name="SHARON SIGAL"></a><b>Sharon Sigal <i>(Lady Angela)</i></b> – is aesthetically pleased to return to RVCO and join the cast for a second round of <i>PATIENCE</i>!  She was Lady Angela in a past RVCO production, as well as Peep Bo in RVCO’s <i>MIKADO</i>.  Sharon was <i>Iolanthe</i>, the title role for IOLANTHE with the Philadelphia Gilbert and Sullivan Union at the G&S festival in Buxton, England, as well as for Thespis, Etc.
Aside from acting and singing for many theaters in and around Philadelphia, Sharon maintains her voice studio in Ardmore where she teaches singing and acting to middle school age children through older adults.  Sharon hosts her Salon of Music and Theater about twice a year, as well as edits and records her own voice-overs for web videos, radio, etc.  Thanks to hubby Jim, daughter Mira and mom, Lillian for their love and support….and to you, the audience-may you all be etherealized – and- too all but! <a href="../../patience/www.sharonsigal.com">www.sharonsigal.com</a> for more information.. <a href="#top"> Back to top</a></li>
  <li><a name="MARTHA SMYLIE"></a><b>Martha Smylie <i>(The Lady Jane)</i></b> – Last seen on our stage as Dame Carruthers (<i>Yeomen</i> 2010), Martha is a former RVCO president, past recipient of our #1 Award, and a proud Life Member, having first joined us in 1981. Born on Arthur Sullivan's birthday, she’s been a life-long fan of G&S and frequently plays Ruth in <i>The Pirates of Penzance</i> for our Music-in-Schools program. As a member of all the G&S groups in the Philadelphia area, she has served four societies as president and is currently Gildmaster of the Ardensingers. Martha has performed in all 14 operas of the G&S canon, most of them many times over, and has sung most of the contralto roles. She has sung in several International G&S Festivals in Buxton (England), Philadelphia, and Gettysburg.  Over the past 25 years she has performed more than 60 roles in Gilbert & Sullivan operas, musicals, dramas and comedies around the Delaware Valley, including nearby Hedgerow Theatre in which building the RVCO debuted in 1907. It’s all about community and the life-long friends we make. <a href="#top"> Back to top</a></li>
		<li><a name="CATHY WAKEFIELD"></a><b>Cathy Wakefield <i>(Rapturous Maiden, Sponsors, Music Librarian)</i></b> is proud to be a Lifetime Member of RVCO and always enjoys singing and dancing with the Chorus. She has performed with the group since the 1981 production of <i>Die Fledermaus</i>. Favorite shows include <i>Guys and Dolls</i> (1984 and 2004), <i>Plain and Fancy</i> (1986 -onstage with her daughter, Kerri), <i>Mame</i> (2007-as Cousin Fan), <i>Oklahoma!</i> (Specialty Woman), and <i>The Pirates of Penzance</i>, her favorite G&S. "Thanks to my wonderful family and friends for their love and support of my exciting hobby!" <a href="#top">Back to top</a></li>
		<li><a name="DAN WILLIAMS"></a><b>Daniel  Williams <i>(The Duke of Dunstable)</i></b> attended West Chester University for voice and theatre. He is currently the Tenor Section Leader at Holy Trinity Episcopal Church in West Chester. Daniel has performed numerous roles in the greater Philadelphia area, including Marco in <i>The Gondoliers,</i> Edwin in <i>Trial by Jury</i>, Camille in <i>The Merry Widow</i> and The Sorcerer in <i>Dido and Aenus</i>. He has also been a featured soloist for performances of Handel's <i>Messiah</i>, Schubert's <i>Mass in G</i>, Orff's <i>Carmina Burana</i> and Saint-Sean's <i>Christmas Oratorio</i>. In addition to performing, Daniel has also directed <i>Trial By Jury</i> with the Gilbert and Sullivan Society of Chester County and will be stage directing Thespis, etc's upcoming production of <i>HMS Pinafore</i> this winter. Daniel is a founding member of Spare Change barbershop quartet and a brother of Phi Mu Alpha Sinfonia. He also sings with The Brandywine Singers. <a href="#top">Back to top</a></li>
	  <li><a name="DAVE ZAFFARANO"></a><b>Dave Zaffarano <i>(Major Murgatroyd,Rehearsal Hospitality,Tickets)</i></b>  Favorite rolls (RVCO): Andrew Carns in <i>Oklahoma!</i>, Ezra in <i>Plain and Fancy</i>, Gregor in <i>Mame</i>,  Pritschitsch in <i>Merry Widow.</i>; Chorus: Mikado, <i>Pirates of Penzance</i>, <i>Ruddigore</i>, <i>H. M. S.Pinafor</i>e. (Ardensingers) Annibale / Francesco in <i>Gondoliers</i>,  Annibale in <i>Pirettes</i> last spring. (GSSCC) Juror in <i>Trial by Jury</i>.   He sings in church as a choir member and a soloist.  He also sings with Schola Cantorum and the Blue and Gray Voices (The St. James Alumni Choir). Thanks Kate for all your Patience.” “Thanks to Julie, my inspiration." <a href="#top">Back to top</a></li>
	  <li><a name="JULIE ZAFFARANO"></a><b>Julie Zaffarano <i>(Lady Ella,Secretary,Rehearsal Hospitality)</i></b> and her husband, Dave, are blessed to be performing in their sixth season with RVCO. Julie's favorite role was being type-cast as Praskowia in <i>The Merry Widow</i> where she flirted violently and (alas!) unsuccessfully. She especially enjoys being a part of RVCO’s Murder Mystery Troupe. Julie has also performed with GSSCC, Ardensingers, and Philadelphia Gilbert and Sullivan Union. She is a founding member of Schola Cantorum and is involved with her church music program. "RVCO is a second family to us! <a href="#top">Back to top</a></li>
</div>
		
	



<p>&nbsp;</p>
</body>
</html>