name: Deploy Sandbox

on:
  push:
    branches:
      - sandbox

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create deployment archive
        run: |
          tar --exclude='.git' \
              --exclude='.github' \
              --exclude='deploy.tar.gz' \
              --warning=no-file-changed \
              -czf deploy.tar.gz .

      - name: Upload to server
        run: |
          scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
              deploy.tar.gz \
              ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/rvco/sandbox/

      - name: Extract on server
        run: |
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
              ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
              "cd /home/rvco/sandbox && tar -xzf deploy.tar.gz && rm deploy.tar.gz"
