name: Deploy to btest

on:
  push:
    branches: [ btest ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Start ssh-agent with private key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy files to /btest
        run: |
          rsync -avz --exclude ".git/" --exclude ".github/" ./ \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/rvco/btest.rvco.org